language: csharp
solution: TrueCraft.sln
mono:
    - latest
before_install:
    - git submodule update --init --recursive
install:
    - nuget restore TrueCraft.sln
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
    - xbuild TrueCraft.sln
    - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TrueCraft.Core.Test/bin/Debug/TrueCraft.Core.Test.dll
